AuthorBookAuthorizedMVC/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuthorBookAuthorizedMVC.Models
{
    public class Book
    {
        public virtual Guid Id { get; set; }
        public virtual string Name { get; set; }
        public virtual string Genre { get; set; }
        public virtual string Description { get; set; }
        public virtual Author Author { get; set; }
    }
}

AuthorBookAuthorizedMVC/Controllers/AuthorDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthorBookAuthorizedMVC.Data;
using AuthorBookAuthorizedMVC.Models;
using NHibernate.Linq;

namespace AuthorBookAuthorizedMVC.Controllers
{
    [Authorize]
    public class AuthorDetailController : Controller
    {
        // GET: AuthorDetail
        public ActionResult GetAuthorDetails()
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var authordetail = session.Query<AuthorDetail>().Fetch(ad => ad.Author).FirstOrDefault(ad => ad.Author.Id == authorId);
                return View(authordetail);
            }
        }
        public ActionResult Edit(Guid id)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var authordetail = session.Query<AuthorDetail>().FirstOrDefault(ad => ad.Author.Id == authorId && ad.Id == id);
                return View(authordetail);
            }
        }
        [HttpPost]
        public ActionResult Edit(AuthorDetail authorDetail)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var existingAuthorDetail = session.Get<AuthorDetail>(authorDetail.Id);
                    existingAuthorDetail.Street = authorDetail.Street;
                    existingAuthorDetail.City = authorDetail.City;
                    existingAuthorDetail.State = authorDetail.State;
                    existingAuthorDetail.Country = authorDetail.Country;
                    existingAuthorDetail.IsActive = true;
                    session.Update(existingAuthorDetail);
                    transaction.Commit();
                    return RedirectToAction("GetAuthorDetails");
                }
            }
        }
        public ActionResult Delete(Guid id)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var authordetail = session.Query<AuthorDetail>().FirstOrDefault(ad => ad.Author.Id == authorId && ad.Id == id);
                return View(authordetail);
            }
        }
        [HttpPost,ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var existingAuthorDetail = session.Get<AuthorDetail>(id);
                    existingAuthorDetail.IsActive = false;
                    existingAuthorDetail.Street = null;
                    existingAuthorDetail.City = null;
                    existingAuthorDetail.State = null;  
                    existingAuthorDetail.Country = null;
                    session.Update(existingAuthorDetail);
                    transaction.Commit();
                    return RedirectToAction("GetAuthorDetails");
                }
            }
        }
    }
}

AuthorBookAuthorizedMVC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthorBookAuthorizedMVC.Data;
using AuthorBookAuthorizedMVC.Models;

namespace AuthorBookAuthorizedMVC.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult GetBooks()
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var books = session.Query<Book>().Where(b => b.Author.Id == authorId).ToList();
                return View(books);
            }
        }
        public ActionResult Edit(Guid id)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var book = session.Query<Book>().FirstOrDefault(b => b.Author.Id == authorId && b.Id == id);
                return View(book);
            }
        }
        [HttpPost]
        public ActionResult Edit(Book book)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var existingBook = session.Get<Book>(book.Id);
                    existingBook.Name = book.Name;
                    existingBook.Genre = book.Genre;
                    existingBook.Description = book.Description;
                    session.Update(existingBook);
                    transaction.Commit();
                    return RedirectToAction("GetBooks");
                }
            }
        }
        public ActionResult Delete(Guid id)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var book = session.Query<Book>().FirstOrDefault(b => b.Author.Id == authorId && b.Id == id);
                return View(book);
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var existingBook = session.Get<Book>(id);
                    session.Delete(existingBook);
                    transaction.Commit();
                    return RedirectToAction("GetBooks");
                }
            }
        }
        public ActionResult Create()
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Create(Book book)
        {
            if (Session["AuthorId"] == null)
            {
                return RedirectToAction("Login", "Author");
            }
            Guid authorId = (Guid)Session["AuthorId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                using(var transaction = session.BeginTransaction())
                {
                    var author = session.Query<Author>().FirstOrDefault(a => a.Id == authorId);
                    book.Author = author;
                    session.Save(book);
                    transaction.Commit();
                    return RedirectToAction("GetBooks");
                }
            }
        }
    }

}

AuthorBookAuthorizedMVC/Views/Book/Create.cshtml
@model AuthorBookAuthorizedMVC.Models.Book

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-dark my-3" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetBooks",null, new { @class = "navbar-brand" })
</div>

AuthorBookAuthorizedMVC/Views/Book/Delete.cshtml
@model AuthorBookAuthorizedMVC.Models.Book

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-outline-dark my-3" /> |
            @Html.ActionLink("Back to List", "GetBooks",null, new { @class = "navbar-brand" })
        </div>
    }
</div>

AuthorBookAuthorizedMVC/Views/Book/Edit.cshtml
@model AuthorBookAuthorizedMVC.Models.Book

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-outline-dark my-3" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetBooks",null, new { @class = "navbar-brand" })
</div>

AuthorBookAuthorizedMVC/Views/Book/GetBooks.cshtml
@model IEnumerable<AuthorBookAuthorizedMVC.Models.Book>

@{
    ViewBag.Title = "GetBooks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetBooks</h2>

<p>
    @Html.ActionLink("Add New Book", "Create",null, new { @class = "navbar-brand" })
</p>
@if (Model != null && Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "navbar-brand" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "navbar-brand" })
                </td>
            </tr>
        }

    </table>
}
else
{
    <p>No books available.</p>
}
<div>
    <p>@Html.ActionLink("View Your Details", "GetAuthorDetails", "AuthorDetail",null, new { @class = "navbar-brand" })</p>
</div>